# in ticks. Usually 20 ticks = 1 second.
teleport-delay: 3

# not recommended to enable. only enable if the dev told you to
debug-mode: false

# Access denied message. Required permission for all subcommands: customspawns.admin
no-permission: "<red><bold>You can not perform this command!"