name: CCustomSpawns
version: ${project.version}
main: dev.crius.ccustomspawns.CCustomSpawnsPlugin
api-version: 1.13
authors: [ CriusTeam, hyperion ]
description: ${project.description}
website: https://crius.dev
commands:
  cspawns:
    aliases:
      - spawns
      - customspawns
      - ccustomspawns
      - criusspawns
      - cspawn